# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95fda531f26054894cec2dd0e1b25f0e75b5f36503f511e244a71589bf8ad7e22a91326fbc81d9dadb20e03f3064b8c13aa3d4d7547fd3e9c9dec2594cafd711

test:
  secret_key_base: 07b5278033f810f0a4650703ae27c9ebd4321ad109316878488be108e1a2d0a2bba6bf08f921e97f0b6eb8b70d4b14d0bbcb9c22d55c1e4aece4c5004d2114af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
